---
- hosts: webservers
  name: configuration play
  become: true
  gather_facts: false
  tasks:
 
  - name: install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
     
  - name: gather_facts
    setup:

- name: Rolling update to iTrust servers
  hosts: webservers
  gather_facts: yes
  serial: 1
  become: yes
  vars:
    itrust_email_user: "itrustuser"
    itrust_email_password: "itrust299"
    packages:
      - python-dev
      - python-pip
      - python-setuptools
      - git-core
      - debconf-utils
      - maven

  tasks:

    # Install all dependencies
    # - name: Set up ppa for maven
    #   apt_repository:
    #     repo: 'ppa:andrei-pozolotin/maven3'
    #     state: "present"
    #   become: yes

    # Install Java 8
    - name: Add repo for Java 8
      apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes
      become: yes

    - name: Add apt repository
      apt_repository:
        repo: 'ppa:webupd8team/java'
        state: present
        update_cache: yes
      become: yes
    
    - name: Accept license
      debconf:
        name: 'oracle-java8-installer'
        question: 'shared/accepted-oracle-license-v1-1'
        value: 'true'
        vtype: 'select'
      become: yes

    - name: Install java
      apt: name={{ item }} state=present
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
      become: yes

    # Install other dependencies
    - name: Install dependencies
      apt:
        pkg: "{{ item }}"
        state: "present"
        update_cache: yes
      with_items: "{{ packages }}"
      become: yes

    # Tomcat setup
    - name: add group "tomcat"
      group: name=tomcat
      become: yes

    - name: add user "tomcat"
      user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
      become: yes

    - name: Check if application repository has already been cloned
      stat:
        path: "/opt/apache-tomcat-9.0.7.tar.gz"
      register: tomcat_tar

    - name: Download Tomcat
      get_url: url=http://www.trieuvan.com/apache/tomcat/tomcat-9/v9.0.7/bin/apache-tomcat-9.0.7.tar.gz dest=/opt/apache-tomcat-9.0.7.tar.gz
      become: yes
      when: tomcat_tar.stat.exists == False

    - name: Check if application repository has already been cloned
      stat:
        path: "/opt/apache-tomcat-9.0.7"
      register: tomcat

    - name: Extract archive
      command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-9.0.7.tar.gz -C /opt/ creates=/opt/apache-tomcat-9.0.7
      become: yes
      when: tomcat.stat.exists == False

    - name: Symlink install directory
      file: src=/opt/apache-tomcat-9.0.7 path=/usr/share/tomcat state=link
      become: yes

    - name: Check if application repository has already been cloned
      stat:
        path: "{{ ansible_env.HOME }}/dev/iTrust2-v2"
      register: itrust_repo

    - name: Copy WAR to /opt/tomcat/webapps
      copy:
        src: /var/lib/jenkins/workspace/iTrust/iTrust2/target/iTrust2.war
        dest: /opt/apache-tomcat-9.0.7/webapps

    - name: start tomcat
      become: yes
      command: nohup /opt/apache-tomcat-9.0.7/bin/startup.sh

    # for human-readable output, run with ANSIBLE_STDOUT_CALLBACK=debug
    - name: print some handy info
      debug:
        msg: |
          Jenkins URL:
            "http://{{ ansible_host }}:8080/iTrust2"
    

